// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package api

// BalanceResponse defines model for BalanceResponse.
type BalanceResponse struct {
	Balance *string `json:"balance,omitempty"`
}

// TransferRequest defines model for TransferRequest.
type TransferRequest struct {
	Amount   *float32 `json:"amount,omitempty"`
	Receiver *int     `json:"receiver,omitempty"`
	Sender   *int     `json:"sender,omitempty"`
}

// TransferResponse defines model for TransferResponse.
type TransferResponse struct {
	Message *string `json:"message,omitempty"`
}

// GetGetBalanceParams defines parameters for GetGetBalance.
type GetGetBalanceParams struct {
	AccountId int32 `form:"account_id" json:"account_id"`
}

// PostTransferJSONRequestBody defines body for PostTransfer for application/json ContentType.
type PostTransferJSONRequestBody = TransferRequest
